name: Check changelog file included

on:
  pull_request:
    paths:
      - 'arthur/**'

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: bitergia/release-tools-check-changelog@main
